//package org.apache.hadoop.rpc.protobuf;
//
//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: CustomProtocol.proto
//
//public final class CustomProtos {
//    private CustomProtos() {
//    }
//
//    public static void registerAllExtensions(
//            com.google.protobuf.ExtensionRegistryLite registry) {
//    }
//
//    public static void registerAllExtensions(
//            com.google.protobuf.ExtensionRegistry registry) {
//        registerAllExtensions(
//                (com.google.protobuf.ExtensionRegistryLite) registry);
//    }
//
//    public interface GetMetaInfoRequestProtoOrBuilder extends
//            // @@protoc_insertion_point(interface_extends:hadoop.common.GetMetaInfoRequestProto)
//            com.google.protobuf.MessageOrBuilder {
//
//        /**
//         * <code>required string path = 1;</code>
//         *
//         * @return Whether the path field is set.
//         */
//        boolean hasPath();
//
//        /**
//         * <code>required string path = 1;</code>
//         *
//         * @return The path.
//         */
//        java.lang.String getPath();
//
//        /**
//         * <code>required string path = 1;</code>
//         *
//         * @return The bytes for path.
//         */
//        com.google.protobuf.ByteString
//        getPathBytes();
//    }
//
//    /**
//     * Protobuf type {@code hadoop.common.GetMetaInfoRequestProto}
//     */
//    public static final class GetMetaInfoRequestProto extends
//            com.google.protobuf.GeneratedMessageV3 implements
//            // @@protoc_insertion_point(message_implements:hadoop.common.GetMetaInfoRequestProto)
//            GetMetaInfoRequestProtoOrBuilder {
//        private static final long serialVersionUID = 0L;
//
//        // Use GetMetaInfoRequestProto.newBuilder() to construct.
//        private GetMetaInfoRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//            super(builder);
//        }
//
//        private GetMetaInfoRequestProto() {
//            path_ = "";
//        }
//
//        @java.lang.Override
//        @SuppressWarnings({"unused"})
//        protected java.lang.Object newInstance(
//                UnusedPrivateParameter unused) {
//            return new GetMetaInfoRequestProto();
//        }
//
//        @java.lang.Override
//        public final com.google.protobuf.UnknownFieldSet
//        getUnknownFields() {
//            return this.unknownFields;
//        }
//
//        public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//            return internal_static_hadoop_common_GetMetaInfoRequestProto_descriptor;
//        }
//
//        @java.lang.Override
//        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//            return internal_static_hadoop_common_GetMetaInfoRequestProto_fieldAccessorTable
//                    .ensureFieldAccessorsInitialized(
//                            org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto.class, org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto.Builder.class);
//        }
//
//        private int bitField0_;
//        public static final int PATH_FIELD_NUMBER = 1;
//        @SuppressWarnings("serial")
//        private volatile java.lang.Object path_ = "";
//
//        /**
//         * <code>required string path = 1;</code>
//         *
//         * @return Whether the path field is set.
//         */
//        @java.lang.Override
//        public boolean hasPath() {
//            return ((bitField0_ & 0x00000001) != 0);
//        }
//
//        /**
//         * <code>required string path = 1;</code>
//         *
//         * @return The path.
//         */
//        @java.lang.Override
//        public java.lang.String getPath() {
//            java.lang.Object ref = path_;
//            if (ref instanceof java.lang.String) {
//                return (java.lang.String) ref;
//            } else {
//                com.google.protobuf.ByteString bs =
//                        (com.google.protobuf.ByteString) ref;
//                java.lang.String s = bs.toStringUtf8();
//                if (bs.isValidUtf8()) {
//                    path_ = s;
//                }
//                return s;
//            }
//        }
//
//        /**
//         * <code>required string path = 1;</code>
//         *
//         * @return The bytes for path.
//         */
//        @java.lang.Override
//        public com.google.protobuf.ByteString
//        getPathBytes() {
//            java.lang.Object ref = path_;
//            if (ref instanceof java.lang.String) {
//                com.google.protobuf.ByteString b =
//                        com.google.protobuf.ByteString.copyFromUtf8(
//                                (java.lang.String) ref);
//                path_ = b;
//                return b;
//            } else {
//                return (com.google.protobuf.ByteString) ref;
//            }
//        }
//
//        private byte memoizedIsInitialized = -1;
//
//        @java.lang.Override
//        public final boolean isInitialized() {
//            byte isInitialized = memoizedIsInitialized;
//            if (isInitialized == 1) return true;
//            if (isInitialized == 0) return false;
//
//            if (!hasPath()) {
//                memoizedIsInitialized = 0;
//                return false;
//            }
//            memoizedIsInitialized = 1;
//            return true;
//        }
//
//        @java.lang.Override
//        public void writeTo(com.google.protobuf.CodedOutputStream output)
//                throws java.io.IOException {
//            if (((bitField0_ & 0x00000001) != 0)) {
//                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
//            }
//            getUnknownFields().writeTo(output);
//        }
//
//        @java.lang.Override
//        public int getSerializedSize() {
//            int size = memoizedSize;
//            if (size != -1) return size;
//
//            size = 0;
//            if (((bitField0_ & 0x00000001) != 0)) {
//                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
//            }
//            size += getUnknownFields().getSerializedSize();
//            memoizedSize = size;
//            return size;
//        }
//
//        @java.lang.Override
//        public boolean equals(final java.lang.Object obj) {
//            if (obj == this) {
//                return true;
//            }
//            if (!(obj instanceof org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto)) {
//                return super.equals(obj);
//            }
//            org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto other = (org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto) obj;
//
//            if (hasPath() != other.hasPath()) return false;
//            if (hasPath()) {
//                if (!getPath()
//                        .equals(other.getPath())) return false;
//            }
//            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
//            return true;
//        }
//
//        @java.lang.Override
//        public int hashCode() {
//            if (memoizedHashCode != 0) {
//                return memoizedHashCode;
//            }
//            int hash = 41;
//            hash = (19 * hash) + getDescriptor().hashCode();
//            if (hasPath()) {
//                hash = (37 * hash) + PATH_FIELD_NUMBER;
//                hash = (53 * hash) + getPath().hashCode();
//            }
//            hash = (29 * hash) + getUnknownFields().hashCode();
//            memoizedHashCode = hash;
//            return hash;
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                java.nio.ByteBuffer data)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                java.nio.ByteBuffer data,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                com.google.protobuf.ByteString data)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                com.google.protobuf.ByteString data,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(byte[] data)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                byte[] data,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(java.io.InputStream input)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                java.io.InputStream input,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseDelimitedFrom(java.io.InputStream input)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseDelimitedWithIOException(PARSER, input);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseDelimitedFrom(
//                java.io.InputStream input,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                com.google.protobuf.CodedInputStream input)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto parseFrom(
//                com.google.protobuf.CodedInputStream input,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input, extensionRegistry);
//        }
//
//        @java.lang.Override
//        public Builder newBuilderForType() {
//            return newBuilder();
//        }
//
//        public static Builder newBuilder() {
//            return DEFAULT_INSTANCE.toBuilder();
//        }
//
//        public static Builder newBuilder(org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto prototype) {
//            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//        }
//
//        @java.lang.Override
//        public Builder toBuilder() {
//            return this == DEFAULT_INSTANCE
//                    ? new Builder() : new Builder().mergeFrom(this);
//        }
//
//        @java.lang.Override
//        protected Builder newBuilderForType(
//                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//            Builder builder = new Builder(parent);
//            return builder;
//        }
//
//        /**
//         * Protobuf type {@code hadoop.common.GetMetaInfoRequestProto}
//         */
//        public static final class Builder extends
//                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//                // @@protoc_insertion_point(builder_implements:hadoop.common.GetMetaInfoRequestProto)
//                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProtoOrBuilder {
//            public static final com.google.protobuf.Descriptors.Descriptor
//            getDescriptor() {
//                return internal_static_hadoop_common_GetMetaInfoRequestProto_descriptor;
//            }
//
//            @java.lang.Override
//            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//            internalGetFieldAccessorTable() {
//                return internal_static_hadoop_common_GetMetaInfoRequestProto_fieldAccessorTable
//                        .ensureFieldAccessorsInitialized(
//                                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto.class, org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto.Builder.class);
//            }
//
//            // Construct using org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto.newBuilder()
//            private Builder() {
//
//            }
//
//            private Builder(
//                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//                super(parent);
//
//            }
//
//            @java.lang.Override
//            public Builder clear() {
//                super.clear();
//                bitField0_ = 0;
//                path_ = "";
//                return this;
//            }
//
//            @java.lang.Override
//            public com.google.protobuf.Descriptors.Descriptor
//            getDescriptorForType() {
//                return internal_static_hadoop_common_GetMetaInfoRequestProto_descriptor;
//            }
//
//            @java.lang.Override
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto getDefaultInstanceForType() {
//                return getDefaultInstance();
//            }
//
//            @java.lang.Override
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto build() {
//                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto result = buildPartial();
//                if (!result.isInitialized()) {
//                    throw newUninitializedMessageException(result);
//                }
//                return result;
//            }
//
//            @java.lang.Override
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto buildPartial() {
//                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto result = new org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto(this);
//                if (bitField0_ != 0) {
//                    buildPartial0(result);
//                }
//                onBuilt();
//                return result;
//            }
//
//            private void buildPartial0(org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto result) {
//                int from_bitField0_ = bitField0_;
//                int to_bitField0_ = 0;
//                if (((from_bitField0_ & 0x00000001) != 0)) {
//                    result.path_ = path_;
//                    to_bitField0_ |= 0x00000001;
//                }
//                result.bitField0_ |= to_bitField0_;
//            }
//
//            @java.lang.Override
//            public Builder clone() {
//                return super.clone();
//            }
//
//            @java.lang.Override
//            public Builder setField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field,
//                    java.lang.Object value) {
//                return super.setField(field, value);
//            }
//
//            @java.lang.Override
//            public Builder clearField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field) {
//                return super.clearField(field);
//            }
//
//            @java.lang.Override
//            public Builder clearOneof(
//                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//                return super.clearOneof(oneof);
//            }
//
//            @java.lang.Override
//            public Builder setRepeatedField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field,
//                    int index, java.lang.Object value) {
//                return super.setRepeatedField(field, index, value);
//            }
//
//            @java.lang.Override
//            public Builder addRepeatedField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field,
//                    java.lang.Object value) {
//                return super.addRepeatedField(field, value);
//            }
//
//            @java.lang.Override
//            public Builder mergeFrom(com.google.protobuf.Message other) {
//                if (other instanceof org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto) {
//                    return mergeFrom((org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto) other);
//                } else {
//                    super.mergeFrom(other);
//                    return this;
//                }
//            }
//
//            public Builder mergeFrom(org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto other) {
//                if (other == getDefaultInstance()) return this;
//                if (other.hasPath()) {
//                    path_ = other.path_;
//                    bitField0_ |= 0x00000001;
//                    onChanged();
//                }
//                this.mergeUnknownFields(other.getUnknownFields());
//                onChanged();
//                return this;
//            }
//
//            @java.lang.Override
//            public final boolean isInitialized() {
//                if (!hasPath()) {
//                    return false;
//                }
//                return true;
//            }
//
//            @java.lang.Override
//            public Builder mergeFrom(
//                    com.google.protobuf.CodedInputStream input,
//                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                    throws java.io.IOException {
//                if (extensionRegistry == null) {
//                    throw new java.lang.NullPointerException();
//                }
//                try {
//                    boolean done = false;
//                    while (!done) {
//                        int tag = input.readTag();
//                        switch (tag) {
//                            case 0:
//                                done = true;
//                                break;
//                            case 10: {
//                                path_ = input.readBytes();
//                                bitField0_ |= 0x00000001;
//                                break;
//                            } // case 10
//                            default: {
//                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                                    done = true; // was an endgroup tag
//                                }
//                                break;
//                            } // default:
//                        } // switch (tag)
//                    } // while (!done)
//                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//                    throw e.unwrapIOException();
//                } finally {
//                    onChanged();
//                } // finally
//                return this;
//            }
//
//            private int bitField0_;
//
//            private java.lang.Object path_ = "";
//
//            /**
//             * <code>required string path = 1;</code>
//             *
//             * @return Whether the path field is set.
//             */
//            public boolean hasPath() {
//                return ((bitField0_ & 0x00000001) != 0);
//            }
//
//            /**
//             * <code>required string path = 1;</code>
//             *
//             * @return The path.
//             */
//            public java.lang.String getPath() {
//                java.lang.Object ref = path_;
//                if (!(ref instanceof java.lang.String)) {
//                    com.google.protobuf.ByteString bs =
//                            (com.google.protobuf.ByteString) ref;
//                    java.lang.String s = bs.toStringUtf8();
//                    if (bs.isValidUtf8()) {
//                        path_ = s;
//                    }
//                    return s;
//                } else {
//                    return (java.lang.String) ref;
//                }
//            }
//
//            /**
//             * <code>required string path = 1;</code>
//             *
//             * @return The bytes for path.
//             */
//            public com.google.protobuf.ByteString
//            getPathBytes() {
//                java.lang.Object ref = path_;
//                if (ref instanceof String) {
//                    com.google.protobuf.ByteString b =
//                            com.google.protobuf.ByteString.copyFromUtf8(
//                                    (java.lang.String) ref);
//                    path_ = b;
//                    return b;
//                } else {
//                    return (com.google.protobuf.ByteString) ref;
//                }
//            }
//
//            /**
//             * <code>required string path = 1;</code>
//             *
//             * @param value The path to set.
//             * @return This builder for chaining.
//             */
//            public Builder setPath(
//                    java.lang.String value) {
//                if (value == null) {
//                    throw new NullPointerException();
//                }
//                path_ = value;
//                bitField0_ |= 0x00000001;
//                onChanged();
//                return this;
//            }
//
//            /**
//             * <code>required string path = 1;</code>
//             *
//             * @return This builder for chaining.
//             */
//            public Builder clearPath() {
//                path_ = getDefaultInstance().getPath();
//                bitField0_ = (bitField0_ & ~0x00000001);
//                onChanged();
//                return this;
//            }
//
//            /**
//             * <code>required string path = 1;</code>
//             *
//             * @param value The bytes for path to set.
//             * @return This builder for chaining.
//             */
//            public Builder setPathBytes(
//                    com.google.protobuf.ByteString value) {
//                if (value == null) {
//                    throw new NullPointerException();
//                }
//                path_ = value;
//                bitField0_ |= 0x00000001;
//                onChanged();
//                return this;
//            }
//
//            @java.lang.Override
//            public final Builder setUnknownFields(
//                    final com.google.protobuf.UnknownFieldSet unknownFields) {
//                return super.setUnknownFields(unknownFields);
//            }
//
//            @java.lang.Override
//            public final Builder mergeUnknownFields(
//                    final com.google.protobuf.UnknownFieldSet unknownFields) {
//                return super.mergeUnknownFields(unknownFields);
//            }
//
//
//            // @@protoc_insertion_point(builder_scope:hadoop.common.GetMetaInfoRequestProto)
//        }
//
//        // @@protoc_insertion_point(class_scope:hadoop.common.GetMetaInfoRequestProto)
//        private static final org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto DEFAULT_INSTANCE;
//
//        static {
//            DEFAULT_INSTANCE = new org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto();
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto getDefaultInstance() {
//            return DEFAULT_INSTANCE;
//        }
//
//        @java.lang.Deprecated
//        public static final com.google.protobuf.Parser<GetMetaInfoRequestProto>
//                PARSER = new com.google.protobuf.AbstractParser<GetMetaInfoRequestProto>() {
//            @java.lang.Override
//            public GetMetaInfoRequestProto parsePartialFrom(
//                    com.google.protobuf.CodedInputStream input,
//                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                    throws com.google.protobuf.InvalidProtocolBufferException {
//                Builder builder = newBuilder();
//                try {
//                    builder.mergeFrom(input, extensionRegistry);
//                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//                    throw e.setUnfinishedMessage(builder.buildPartial());
//                } catch (com.google.protobuf.UninitializedMessageException e) {
//                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
//                } catch (java.io.IOException e) {
//                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
//                            .setUnfinishedMessage(builder.buildPartial());
//                }
//                return builder.buildPartial();
//            }
//        };
//
//        public static com.google.protobuf.Parser<GetMetaInfoRequestProto> parser() {
//            return PARSER;
//        }
//
//        @java.lang.Override
//        public com.google.protobuf.Parser<GetMetaInfoRequestProto> getParserForType() {
//            return PARSER;
//        }
//
//        @java.lang.Override
//        public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto getDefaultInstanceForType() {
//            return DEFAULT_INSTANCE;
//        }
//
//    }
//
//    public interface GetMetaInfoResponseProtoOrBuilder extends
//            // @@protoc_insertion_point(interface_extends:hadoop.common.GetMetaInfoResponseProto)
//            com.google.protobuf.MessageOrBuilder {
//
//        /**
//         * <code>required string info = 1;</code>
//         *
//         * @return Whether the info field is set.
//         */
//        boolean hasInfo();
//
//        /**
//         * <code>required string info = 1;</code>
//         *
//         * @return The info.
//         */
//        java.lang.String getInfo();
//
//        /**
//         * <code>required string info = 1;</code>
//         *
//         * @return The bytes for info.
//         */
//        com.google.protobuf.ByteString
//        getInfoBytes();
//    }
//
//    /**
//     * Protobuf type {@code hadoop.common.GetMetaInfoResponseProto}
//     */
//    public static final class GetMetaInfoResponseProto extends
//            com.google.protobuf.GeneratedMessageV3 implements
//            // @@protoc_insertion_point(message_implements:hadoop.common.GetMetaInfoResponseProto)
//            GetMetaInfoResponseProtoOrBuilder {
//        private static final long serialVersionUID = 0L;
//
//        // Use GetMetaInfoResponseProto.newBuilder() to construct.
//        private GetMetaInfoResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//            super(builder);
//        }
//
//        private GetMetaInfoResponseProto() {
//            info_ = "";
//        }
//
//        @java.lang.Override
//        @SuppressWarnings({"unused"})
//        protected java.lang.Object newInstance(
//                UnusedPrivateParameter unused) {
//            return new GetMetaInfoResponseProto();
//        }
//
//        @java.lang.Override
//        public final com.google.protobuf.UnknownFieldSet
//        getUnknownFields() {
//            return this.unknownFields;
//        }
//
//        public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//            return internal_static_hadoop_common_GetMetaInfoResponseProto_descriptor;
//        }
//
//        @java.lang.Override
//        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//            return internal_static_hadoop_common_GetMetaInfoResponseProto_fieldAccessorTable
//                    .ensureFieldAccessorsInitialized(
//                            org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.class, org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.Builder.class);
//        }
//
//        private int bitField0_;
//        public static final int INFO_FIELD_NUMBER = 1;
//        @SuppressWarnings("serial")
//        private volatile java.lang.Object info_ = "";
//
//        /**
//         * <code>required string info = 1;</code>
//         *
//         * @return Whether the info field is set.
//         */
//        @java.lang.Override
//        public boolean hasInfo() {
//            return ((bitField0_ & 0x00000001) != 0);
//        }
//
//        /**
//         * <code>required string info = 1;</code>
//         *
//         * @return The info.
//         */
//        @java.lang.Override
//        public java.lang.String getInfo() {
//            java.lang.Object ref = info_;
//            if (ref instanceof java.lang.String) {
//                return (java.lang.String) ref;
//            } else {
//                com.google.protobuf.ByteString bs =
//                        (com.google.protobuf.ByteString) ref;
//                java.lang.String s = bs.toStringUtf8();
//                if (bs.isValidUtf8()) {
//                    info_ = s;
//                }
//                return s;
//            }
//        }
//
//        /**
//         * <code>required string info = 1;</code>
//         *
//         * @return The bytes for info.
//         */
//        @java.lang.Override
//        public com.google.protobuf.ByteString
//        getInfoBytes() {
//            java.lang.Object ref = info_;
//            if (ref instanceof java.lang.String) {
//                com.google.protobuf.ByteString b =
//                        com.google.protobuf.ByteString.copyFromUtf8(
//                                (java.lang.String) ref);
//                info_ = b;
//                return b;
//            } else {
//                return (com.google.protobuf.ByteString) ref;
//            }
//        }
//
//        private byte memoizedIsInitialized = -1;
//
//        @java.lang.Override
//        public final boolean isInitialized() {
//            byte isInitialized = memoizedIsInitialized;
//            if (isInitialized == 1) return true;
//            if (isInitialized == 0) return false;
//
//            if (!hasInfo()) {
//                memoizedIsInitialized = 0;
//                return false;
//            }
//            memoizedIsInitialized = 1;
//            return true;
//        }
//
//        @java.lang.Override
//        public void writeTo(com.google.protobuf.CodedOutputStream output)
//                throws java.io.IOException {
//            if (((bitField0_ & 0x00000001) != 0)) {
//                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, info_);
//            }
//            getUnknownFields().writeTo(output);
//        }
//
//        @java.lang.Override
//        public int getSerializedSize() {
//            int size = memoizedSize;
//            if (size != -1) return size;
//
//            size = 0;
//            if (((bitField0_ & 0x00000001) != 0)) {
//                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, info_);
//            }
//            size += getUnknownFields().getSerializedSize();
//            memoizedSize = size;
//            return size;
//        }
//
//        @java.lang.Override
//        public boolean equals(final java.lang.Object obj) {
//            if (obj == this) {
//                return true;
//            }
//            if (!(obj instanceof org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto)) {
//                return super.equals(obj);
//            }
//            org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto other = (org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto) obj;
//
//            if (hasInfo() != other.hasInfo()) return false;
//            if (hasInfo()) {
//                if (!getInfo()
//                        .equals(other.getInfo())) return false;
//            }
//            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
//            return true;
//        }
//
//        @java.lang.Override
//        public int hashCode() {
//            if (memoizedHashCode != 0) {
//                return memoizedHashCode;
//            }
//            int hash = 41;
//            hash = (19 * hash) + getDescriptor().hashCode();
//            if (hasInfo()) {
//                hash = (37 * hash) + INFO_FIELD_NUMBER;
//                hash = (53 * hash) + getInfo().hashCode();
//            }
//            hash = (29 * hash) + getUnknownFields().hashCode();
//            memoizedHashCode = hash;
//            return hash;
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                java.nio.ByteBuffer data)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                java.nio.ByteBuffer data,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                com.google.protobuf.ByteString data)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                com.google.protobuf.ByteString data,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(byte[] data)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                byte[] data,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws com.google.protobuf.InvalidProtocolBufferException {
//            return PARSER.parseFrom(data, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(java.io.InputStream input)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                java.io.InputStream input,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseDelimitedFrom(java.io.InputStream input)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseDelimitedWithIOException(PARSER, input);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseDelimitedFrom(
//                java.io.InputStream input,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                com.google.protobuf.CodedInputStream input)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input);
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto parseFrom(
//                com.google.protobuf.CodedInputStream input,
//                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                throws java.io.IOException {
//            return com.google.protobuf.GeneratedMessageV3
//                    .parseWithIOException(PARSER, input, extensionRegistry);
//        }
//
//        @java.lang.Override
//        public Builder newBuilderForType() {
//            return newBuilder();
//        }
//
//        public static Builder newBuilder() {
//            return DEFAULT_INSTANCE.toBuilder();
//        }
//
//        public static Builder newBuilder(org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto prototype) {
//            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//        }
//
//        @java.lang.Override
//        public Builder toBuilder() {
//            return this == DEFAULT_INSTANCE
//                    ? new Builder() : new Builder().mergeFrom(this);
//        }
//
//        @java.lang.Override
//        protected Builder newBuilderForType(
//                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//            Builder builder = new Builder(parent);
//            return builder;
//        }
//
//        /**
//         * Protobuf type {@code hadoop.common.GetMetaInfoResponseProto}
//         */
//        public static final class Builder extends
//                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//                // @@protoc_insertion_point(builder_implements:hadoop.common.GetMetaInfoResponseProto)
//                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProtoOrBuilder {
//            public static final com.google.protobuf.Descriptors.Descriptor
//            getDescriptor() {
//                return internal_static_hadoop_common_GetMetaInfoResponseProto_descriptor;
//            }
//
//            @java.lang.Override
//            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//            internalGetFieldAccessorTable() {
//                return internal_static_hadoop_common_GetMetaInfoResponseProto_fieldAccessorTable
//                        .ensureFieldAccessorsInitialized(
//                                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.class, org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.Builder.class);
//            }
//
//            // Construct using org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.newBuilder()
//            private Builder() {
//
//            }
//
//            private Builder(
//                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//                super(parent);
//
//            }
//
//            @java.lang.Override
//            public Builder clear() {
//                super.clear();
//                bitField0_ = 0;
//                info_ = "";
//                return this;
//            }
//
//            @java.lang.Override
//            public com.google.protobuf.Descriptors.Descriptor
//            getDescriptorForType() {
//                return internal_static_hadoop_common_GetMetaInfoResponseProto_descriptor;
//            }
//
//            @java.lang.Override
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto getDefaultInstanceForType() {
//                return getDefaultInstance();
//            }
//
//            @java.lang.Override
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto build() {
//                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto result = buildPartial();
//                if (!result.isInitialized()) {
//                    throw newUninitializedMessageException(result);
//                }
//                return result;
//            }
//
//            @java.lang.Override
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto buildPartial() {
//                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto result = new org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto(this);
//                if (bitField0_ != 0) {
//                    buildPartial0(result);
//                }
//                onBuilt();
//                return result;
//            }
//
//            private void buildPartial0(org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto result) {
//                int from_bitField0_ = bitField0_;
//                int to_bitField0_ = 0;
//                if (((from_bitField0_ & 0x00000001) != 0)) {
//                    result.info_ = info_;
//                    to_bitField0_ |= 0x00000001;
//                }
//                result.bitField0_ |= to_bitField0_;
//            }
//
//            @java.lang.Override
//            public Builder clone() {
//                return super.clone();
//            }
//
//            @java.lang.Override
//            public Builder setField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field,
//                    java.lang.Object value) {
//                return super.setField(field, value);
//            }
//
//            @java.lang.Override
//            public Builder clearField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field) {
//                return super.clearField(field);
//            }
//
//            @java.lang.Override
//            public Builder clearOneof(
//                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//                return super.clearOneof(oneof);
//            }
//
//            @java.lang.Override
//            public Builder setRepeatedField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field,
//                    int index, java.lang.Object value) {
//                return super.setRepeatedField(field, index, value);
//            }
//
//            @java.lang.Override
//            public Builder addRepeatedField(
//                    com.google.protobuf.Descriptors.FieldDescriptor field,
//                    java.lang.Object value) {
//                return super.addRepeatedField(field, value);
//            }
//
//            @java.lang.Override
//            public Builder mergeFrom(com.google.protobuf.Message other) {
//                if (other instanceof org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto) {
//                    return mergeFrom((org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto) other);
//                } else {
//                    super.mergeFrom(other);
//                    return this;
//                }
//            }
//
//            public Builder mergeFrom(org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto other) {
//                if (other == getDefaultInstance()) return this;
//                if (other.hasInfo()) {
//                    info_ = other.info_;
//                    bitField0_ |= 0x00000001;
//                    onChanged();
//                }
//                this.mergeUnknownFields(other.getUnknownFields());
//                onChanged();
//                return this;
//            }
//
//            @java.lang.Override
//            public final boolean isInitialized() {
//                if (!hasInfo()) {
//                    return false;
//                }
//                return true;
//            }
//
//            @java.lang.Override
//            public Builder mergeFrom(
//                    com.google.protobuf.CodedInputStream input,
//                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                    throws java.io.IOException {
//                if (extensionRegistry == null) {
//                    throw new java.lang.NullPointerException();
//                }
//                try {
//                    boolean done = false;
//                    while (!done) {
//                        int tag = input.readTag();
//                        switch (tag) {
//                            case 0:
//                                done = true;
//                                break;
//                            case 10: {
//                                info_ = input.readBytes();
//                                bitField0_ |= 0x00000001;
//                                break;
//                            } // case 10
//                            default: {
//                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                                    done = true; // was an endgroup tag
//                                }
//                                break;
//                            } // default:
//                        } // switch (tag)
//                    } // while (!done)
//                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//                    throw e.unwrapIOException();
//                } finally {
//                    onChanged();
//                } // finally
//                return this;
//            }
//
//            private int bitField0_;
//
//            private java.lang.Object info_ = "";
//
//            /**
//             * <code>required string info = 1;</code>
//             *
//             * @return Whether the info field is set.
//             */
//            public boolean hasInfo() {
//                return ((bitField0_ & 0x00000001) != 0);
//            }
//
//            /**
//             * <code>required string info = 1;</code>
//             *
//             * @return The info.
//             */
//            public java.lang.String getInfo() {
//                java.lang.Object ref = info_;
//                if (!(ref instanceof java.lang.String)) {
//                    com.google.protobuf.ByteString bs =
//                            (com.google.protobuf.ByteString) ref;
//                    java.lang.String s = bs.toStringUtf8();
//                    if (bs.isValidUtf8()) {
//                        info_ = s;
//                    }
//                    return s;
//                } else {
//                    return (java.lang.String) ref;
//                }
//            }
//
//            /**
//             * <code>required string info = 1;</code>
//             *
//             * @return The bytes for info.
//             */
//            public com.google.protobuf.ByteString
//            getInfoBytes() {
//                java.lang.Object ref = info_;
//                if (ref instanceof String) {
//                    com.google.protobuf.ByteString b =
//                            com.google.protobuf.ByteString.copyFromUtf8(
//                                    (java.lang.String) ref);
//                    info_ = b;
//                    return b;
//                } else {
//                    return (com.google.protobuf.ByteString) ref;
//                }
//            }
//
//            /**
//             * <code>required string info = 1;</code>
//             *
//             * @param value The info to set.
//             * @return This builder for chaining.
//             */
//            public Builder setInfo(
//                    java.lang.String value) {
//                if (value == null) {
//                    throw new NullPointerException();
//                }
//                info_ = value;
//                bitField0_ |= 0x00000001;
//                onChanged();
//                return this;
//            }
//
//            /**
//             * <code>required string info = 1;</code>
//             *
//             * @return This builder for chaining.
//             */
//            public Builder clearInfo() {
//                info_ = getDefaultInstance().getInfo();
//                bitField0_ = (bitField0_ & ~0x00000001);
//                onChanged();
//                return this;
//            }
//
//            /**
//             * <code>required string info = 1;</code>
//             *
//             * @param value The bytes for info to set.
//             * @return This builder for chaining.
//             */
//            public Builder setInfoBytes(
//                    com.google.protobuf.ByteString value) {
//                if (value == null) {
//                    throw new NullPointerException();
//                }
//                info_ = value;
//                bitField0_ |= 0x00000001;
//                onChanged();
//                return this;
//            }
//
//            @java.lang.Override
//            public final Builder setUnknownFields(
//                    final com.google.protobuf.UnknownFieldSet unknownFields) {
//                return super.setUnknownFields(unknownFields);
//            }
//
//            @java.lang.Override
//            public final Builder mergeUnknownFields(
//                    final com.google.protobuf.UnknownFieldSet unknownFields) {
//                return super.mergeUnknownFields(unknownFields);
//            }
//
//
//            // @@protoc_insertion_point(builder_scope:hadoop.common.GetMetaInfoResponseProto)
//        }
//
//        // @@protoc_insertion_point(class_scope:hadoop.common.GetMetaInfoResponseProto)
//        private static final org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto DEFAULT_INSTANCE;
//
//        static {
//            DEFAULT_INSTANCE = new org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto();
//        }
//
//        public static org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto getDefaultInstance() {
//            return DEFAULT_INSTANCE;
//        }
//
//        @java.lang.Deprecated
//        public static final com.google.protobuf.Parser<GetMetaInfoResponseProto>
//                PARSER = new com.google.protobuf.AbstractParser<GetMetaInfoResponseProto>() {
//            @java.lang.Override
//            public GetMetaInfoResponseProto parsePartialFrom(
//                    com.google.protobuf.CodedInputStream input,
//                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//                    throws com.google.protobuf.InvalidProtocolBufferException {
//                Builder builder = newBuilder();
//                try {
//                    builder.mergeFrom(input, extensionRegistry);
//                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//                    throw e.setUnfinishedMessage(builder.buildPartial());
//                } catch (com.google.protobuf.UninitializedMessageException e) {
//                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
//                } catch (java.io.IOException e) {
//                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
//                            .setUnfinishedMessage(builder.buildPartial());
//                }
//                return builder.buildPartial();
//            }
//        };
//
//        public static com.google.protobuf.Parser<GetMetaInfoResponseProto> parser() {
//            return PARSER;
//        }
//
//        @java.lang.Override
//        public com.google.protobuf.Parser<GetMetaInfoResponseProto> getParserForType() {
//            return PARSER;
//        }
//
//        @java.lang.Override
//        public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto getDefaultInstanceForType() {
//            return DEFAULT_INSTANCE;
//        }
//
//    }
//
//    /**
//     * Protobuf service {@code hadoop.common.MetaInfo}
//     */
//    public static abstract class MetaInfo
//            implements com.google.protobuf.Service {
//        protected MetaInfo() {
//        }
//
//        public interface Interface {
//            /**
//             * <code>rpc getMetaInfo(.hadoop.common.GetMetaInfoRequestProto) returns (.hadoop.common.GetMetaInfoResponseProto);</code>
//             */
//            public abstract void getMetaInfo(
//                    com.google.protobuf.RpcController controller,
//                    org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto request,
//                    com.google.protobuf.RpcCallback<org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto> done);
//
//        }
//
//        public static com.google.protobuf.Service newReflectiveService(
//                final Interface impl) {
//            return new MetaInfo() {
//                @java.lang.Override
//                public void getMetaInfo(
//                        com.google.protobuf.RpcController controller,
//                        org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto request,
//                        com.google.protobuf.RpcCallback<org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto> done) {
//                    impl.getMetaInfo(controller, request, done);
//                }
//
//            };
//        }
//
//        public static com.google.protobuf.BlockingService
//        newReflectiveBlockingService(final BlockingInterface impl) {
//            return new com.google.protobuf.BlockingService() {
//                public final com.google.protobuf.Descriptors.ServiceDescriptor
//                getDescriptorForType() {
//                    return getDescriptor();
//                }
//
//                public final com.google.protobuf.Message callBlockingMethod(
//                        com.google.protobuf.Descriptors.MethodDescriptor method,
//                        com.google.protobuf.RpcController controller,
//                        com.google.protobuf.Message request)
//                        throws com.google.protobuf.ServiceException {
//                    if (method.getService() != getDescriptor()) {
//                        throw new java.lang.IllegalArgumentException(
//                                "Service.callBlockingMethod() given method descriptor for " +
//                                        "wrong service type.");
//                    }
//                    switch (method.getIndex()) {
//                        case 0:
//                            return impl.getMetaInfo(controller, (org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto) request);
//                        default:
//                            throw new java.lang.AssertionError("Can't get here.");
//                    }
//                }
//
//                public final com.google.protobuf.Message
//                getRequestPrototype(
//                        com.google.protobuf.Descriptors.MethodDescriptor method) {
//                    if (method.getService() != getDescriptor()) {
//                        throw new java.lang.IllegalArgumentException(
//                                "Service.getRequestPrototype() given method " +
//                                        "descriptor for wrong service type.");
//                    }
//                    switch (method.getIndex()) {
//                        case 0:
//                            return org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto.getDefaultInstance();
//                        default:
//                            throw new java.lang.AssertionError("Can't get here.");
//                    }
//                }
//
//                public final com.google.protobuf.Message
//                getResponsePrototype(
//                        com.google.protobuf.Descriptors.MethodDescriptor method) {
//                    if (method.getService() != getDescriptor()) {
//                        throw new java.lang.IllegalArgumentException(
//                                "Service.getResponsePrototype() given method " +
//                                        "descriptor for wrong service type.");
//                    }
//                    switch (method.getIndex()) {
//                        case 0:
//                            return org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.getDefaultInstance();
//                        default:
//                            throw new java.lang.AssertionError("Can't get here.");
//                    }
//                }
//
//            };
//        }
//
//        /**
//         * <code>rpc getMetaInfo(.hadoop.common.GetMetaInfoRequestProto) returns (.hadoop.common.GetMetaInfoResponseProto);</code>
//         */
//        public abstract void getMetaInfo(
//                com.google.protobuf.RpcController controller,
//                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto request,
//                com.google.protobuf.RpcCallback<org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto> done);
//
//        public static final com.google.protobuf.Descriptors.ServiceDescriptor
//        getDescriptor() {
//            return org.apache.hadoop.rpc.protobuf.CustomProtos.getDescriptor().getServices().get(0);
//        }
//
//        public final com.google.protobuf.Descriptors.ServiceDescriptor
//        getDescriptorForType() {
//            return getDescriptor();
//        }
//
//        public final void callMethod(
//                com.google.protobuf.Descriptors.MethodDescriptor method,
//                com.google.protobuf.RpcController controller,
//                com.google.protobuf.Message request,
//                com.google.protobuf.RpcCallback<
//                        com.google.protobuf.Message> done) {
//            if (method.getService() != getDescriptor()) {
//                throw new java.lang.IllegalArgumentException(
//                        "Service.callMethod() given method descriptor for wrong " +
//                                "service type.");
//            }
//            switch (method.getIndex()) {
//                case 0:
//                    this.getMetaInfo(controller, (org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto) request,
//                            com.google.protobuf.RpcUtil.<org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto>specializeCallback(
//                                    done));
//                    return;
//                default:
//                    throw new java.lang.AssertionError("Can't get here.");
//            }
//        }
//
//        public final com.google.protobuf.Message
//        getRequestPrototype(
//                com.google.protobuf.Descriptors.MethodDescriptor method) {
//            if (method.getService() != getDescriptor()) {
//                throw new java.lang.IllegalArgumentException(
//                        "Service.getRequestPrototype() given method " +
//                                "descriptor for wrong service type.");
//            }
//            switch (method.getIndex()) {
//                case 0:
//                    return org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto.getDefaultInstance();
//                default:
//                    throw new java.lang.AssertionError("Can't get here.");
//            }
//        }
//
//        public final com.google.protobuf.Message
//        getResponsePrototype(
//                com.google.protobuf.Descriptors.MethodDescriptor method) {
//            if (method.getService() != getDescriptor()) {
//                throw new java.lang.IllegalArgumentException(
//                        "Service.getResponsePrototype() given method " +
//                                "descriptor for wrong service type.");
//            }
//            switch (method.getIndex()) {
//                case 0:
//                    return org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.getDefaultInstance();
//                default:
//                    throw new java.lang.AssertionError("Can't get here.");
//            }
//        }
//
//        public static Stub newStub(
//                com.google.protobuf.RpcChannel channel) {
//            return new Stub(channel);
//        }
//
//        public static final class Stub extends org.apache.hadoop.rpc.protobuf.CustomProtos.MetaInfo implements Interface {
//            private Stub(com.google.protobuf.RpcChannel channel) {
//                this.channel = channel;
//            }
//
//            private final com.google.protobuf.RpcChannel channel;
//
//            public com.google.protobuf.RpcChannel getChannel() {
//                return channel;
//            }
//
//            public void getMetaInfo(
//                    com.google.protobuf.RpcController controller,
//                    org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto request,
//                    com.google.protobuf.RpcCallback<org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto> done) {
//                channel.callMethod(
//                        getDescriptor().getMethods().get(0),
//                        controller,
//                        request,
//                        org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.getDefaultInstance(),
//                        com.google.protobuf.RpcUtil.generalizeCallback(
//                                done,
//                                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.class,
//                                org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.getDefaultInstance()));
//            }
//        }
//
//        public static BlockingInterface newBlockingStub(
//                com.google.protobuf.BlockingRpcChannel channel) {
//            return new BlockingStub(channel);
//        }
//
//        public interface BlockingInterface {
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto getMetaInfo(
//                    com.google.protobuf.RpcController controller,
//                    org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto request)
//                    throws com.google.protobuf.ServiceException;
//        }
//
//        private static final class BlockingStub implements BlockingInterface {
//            private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
//                this.channel = channel;
//            }
//
//            private final com.google.protobuf.BlockingRpcChannel channel;
//
//            public org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto getMetaInfo(
//                    com.google.protobuf.RpcController controller,
//                    org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoRequestProto request)
//                    throws com.google.protobuf.ServiceException {
//                return (org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto) channel.callBlockingMethod(
//                        getDescriptor().getMethods().get(0),
//                        controller,
//                        request,
//                        org.apache.hadoop.rpc.protobuf.CustomProtos.GetMetaInfoResponseProto.getDefaultInstance());
//            }
//
//        }
//
//        // @@protoc_insertion_point(class_scope:hadoop.common.MetaInfo)
//    }
//
//    private static final com.google.protobuf.Descriptors.Descriptor
//            internal_static_hadoop_common_GetMetaInfoRequestProto_descriptor;
//    private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//            internal_static_hadoop_common_GetMetaInfoRequestProto_fieldAccessorTable;
//    private static final com.google.protobuf.Descriptors.Descriptor
//            internal_static_hadoop_common_GetMetaInfoResponseProto_descriptor;
//    private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//            internal_static_hadoop_common_GetMetaInfoResponseProto_fieldAccessorTable;
//
//    public static com.google.protobuf.Descriptors.FileDescriptor
//    getDescriptor() {
//        return descriptor;
//    }
//
//    private static com.google.protobuf.Descriptors.FileDescriptor
//            descriptor;
//
//    static {
//        java.lang.String[] descriptorData = {
//                "\n\024CustomProtocol.proto\022\rhadoop.common\"\'\n" +
//                        "\027GetMetaInfoRequestProto\022\014\n\004path\030\001 \002(\t\"(" +
//                        "\n\030GetMetaInfoResponseProto\022\014\n\004info\030\001 \002(\t" +
//                        "2j\n\010MetaInfo\022^\n\013getMetaInfo\022&.hadoop.com" +
//                        "mon.GetMetaInfoRequestProto\032\'.hadoop.com" +
//                        "mon.GetMetaInfoResponseProtoB4\n\036org.apac" +
//                        "he.hadoop.rpc.protobufB\014CustomProtos\210\001\001\240" +
//                        "\001\001"
//        };
//        descriptor = com.google.protobuf.Descriptors.FileDescriptor
//                .internalBuildGeneratedFileFrom(descriptorData,
//                        new com.google.protobuf.Descriptors.FileDescriptor[]{
//                        });
//        internal_static_hadoop_common_GetMetaInfoRequestProto_descriptor =
//                getDescriptor().getMessageTypes().get(0);
//        internal_static_hadoop_common_GetMetaInfoRequestProto_fieldAccessorTable = new
//                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//                internal_static_hadoop_common_GetMetaInfoRequestProto_descriptor,
//                new java.lang.String[]{"Path",});
//        internal_static_hadoop_common_GetMetaInfoResponseProto_descriptor =
//                getDescriptor().getMessageTypes().get(1);
//        internal_static_hadoop_common_GetMetaInfoResponseProto_fieldAccessorTable = new
//                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//                internal_static_hadoop_common_GetMetaInfoResponseProto_descriptor,
//                new java.lang.String[]{"Info",});
//    }
//
//    // @@protoc_insertion_point(outer_class_scope)
//}
